export const facts = [
    "Maintaining good oral hygiene can lower the risk of cardiovascular disease by reducing inflammation and harmful bacteria in the mouth.",
    "Consuming a diet rich in omega-3 fatty acids, found in foods like salmon and walnuts, can improve brain health and cognitive function.",
    "Adequate sleep enhances creativity and problem-solving skills, as it allows the brain to consolidate information and make novel connections.",
    "Studying in natural environments, such as parks or gardens, can boost concentration, memory retention, and overall academic performance.",
    "Regular resistance training not only strengthens muscles but also improves bone density, reducing the risk of osteoporosis and fractures.",
    "Proper hand hygiene, including thorough handwashing, is one of the most effective ways to prevent the spread of infectious diseases.",
    "Eating a balanced breakfast can enhance mood and cognitive performance throughout the day, as it provides essential nutrients and stabilizes blood sugar levels.",
    "Maintaining a consistent sleep schedule helps regulate the body's internal clock, improving sleep quality and reducing the risk of sleep disorders.",
    "Regular physical exercise boosts the production of endorphins, natural chemicals that promote a sense of well-being and reduce stress.",
    "Incorporating short breaks during study sessions can improve focus and information retention, as the brain benefits from intermittent rest.",
    "Practicing good posture while studying or working can prevent musculoskeletal issues and improve overall comfort and productivity.",
    "Aromatherapy using essential oils like lavender can promote relaxation, reduce anxiety, and improve sleep quality.",
    "Regular cardiovascular exercise stimulates the growth of new brain cells, enhancing learning and memory abilities.",
    "Taking frequent breaks during exercise sessions can help prevent overexertion and reduce the risk of injury.",
    "Studies suggest that listening to classical music while studying can enhance cognitive performance and improve concentration levels.",
    "Brushing your teeth with your non-dominant hand can improve motor skills and cognitive flexibility, stimulating different areas of the brain.",
    "Eating a diet rich in antioxidants, such as fruits and vegetables, can help protect against age-related cognitive decline and neurodegenerative diseases.",
    "Creating a calm and organized study space can improve focus, reduce distractions, and enhance productivity.",
    "Engaging in moderate-intensity aerobic exercise before bed can promote better sleep by reducing anxiety and promoting relaxation.",
    "Regular physical activity has been shown to alleviate symptoms of depression and anxiety, boosting overall mental well-being.",
    "Practicing good sleep hygiene, such as avoiding screens before bed, can promote better sleep quality and reduce the time it takes to fall asleep.",
    "Consuming foods high in magnesium, such as spinach and almonds, can help regulate sleep patterns and improve sleep quality.",
    "Regularly engaging in mentally challenging activities, like puzzles or learning a new instrument, can enhance cognitive function and prevent cognitive decline.",
    "Maintaining a clean and clutter-free study environment can reduce stress levels and improve focus and productivity.",
    "Stretching before and after exercise helps improve flexibility, prevent injuries, and promote better muscle recovery.",
    "A warm bath or shower before bed can help relax the body and signal the brain that it's time to sleep, leading to better sleep quality.",
    "Incorporating regular meditation or mindfulness practices into daily life can reduce stress, improve focus, and promote emotional well-being.",
    "Eating foods high in tryptophan, such as turkey or tofu, can promote the production of serotonin, a neurotransmitter that contributes to mood regulation and better sleep.",
    "Regular aerobic exercise has been found to enhance the growth and development of new neurons in the brain, improving overall cognitive function.",
    "Using flashcards as a study tool can enhance memory retention and improve recall abilities by engaging active recall and spaced repetition techniques.",
    "Exercising in natural environments, such as forests or beaches, can improve mood and self-esteem while reducing feelings of anxiety or depression.",
    "Consuming a balanced diet that includes foods rich in vitamins and minerals, such as leafy greens and lean proteins, supports overall health and well-being.",
    "Practicing deep breathing exercises during studying or before exams can help reduce stress, improve focus, and enhance mental clarity.",
    "Regular resistance training not only increases muscle strength but also improves bone health, reducing the risk of osteoporosis and fractures.",
    "Maintaining good personal hygiene, including regular handwashing, can significantly reduce the transmission of infectious diseases and protect overall health.",
    "Eating a high-protein meal or snack before studying or taking an exam can enhance alertness and cognitive performance.",
    "Having a consistent and relaxing bedtime routine can signal the body to prepare for sleep, leading to more restful nights and improved sleep quality.",
    "Incorporating interval training into your exercise routine can boost metabolism, burn more calories, and improve cardiovascular fitness more efficiently.",
    "Regularly reviewing and summarizing study materials can improve comprehension and retention of information by reinforcing key concepts.",
    "Engaging in regular physical exercise not only improves physical health but also releases endorphins that elevate mood, reducing the risk of depression and anxiety."
]